create table regions(
    region_id serial primary key,
    REGION_NAME varchar(25)
);
CREATE TABLE locations(
    LOCATION_ID BIGINT PRIMARY KEY,
    STREET_ADDRESS VARCHAR(25),
    POSTAL_CODE VARCHAR(12),
    CITY VARCHAR(30),
    STATE_PROVINCE VARCHAR(20),
    COUNTRY_ID CHAR(2) REFERENCES countries(COUNTRY_ID)
    );
CREATE TABLE countries(
COUNTRY_ID CHAR(2)  PRIMARY KEY,
COUNTRY_NAME VARCHAR(40) ,
REGION_ID INT  REFERENCES regions(REGION_ID)
);